name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Install job dependencies
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - uses: reviewdog/action-setup@d8edfce3dd5e1ec6978745e801f9c50b5ef80252
        with:
          reviewdog_version: v0.20.3

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Format
        if: ${{ !cancelled() }}
        run: |
          uvx ruff format --diff \
            | reviewdog -f=diff -name="ruff format" -reporter=github-pr-review -filter-mode=nofilter -fail-level=any

      - name: Lint
        if: ${{ !cancelled() }}
        run: |
          uvx ruff check --output-format rdjson \
            | reviewdog -f=rdjson -name="ruff lint" -reporter=github-pr-review -filter-mode=nofilter -fail-level=none

      - name: Type Check
        if: ${{ !cancelled() }}
        run: |
          uvx ty check --output-format github \
            | reviewdog -f=ty -name="ty type check" -reporter=github-pr-review -filter-mode=nofilter -fail-level=none
